import { useState } from 'react';
import { ArrowUpRight, CheckCircle2, ShieldCheck, Activity, Eye, RotateCcw } from 'lucide-react';
import { Link } from '@tanstack/react-router';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '../components/ui/card';
import { Badge } from '../components/ui/badge';
import { Button } from '../components/ui/button';
import { useI18n } from '../context/i18n';

const signals = [{ key: 'quality', value: 94, icon: CheckCircle2, color: 'text-emerald-500' }, { key: 'reliability', value: 88, icon: ShieldCheck, color: 'text-blue-500' }, { key: 'observability', value: 91, icon: Eye, color: 'text-violet-500' }, { key: 'rollback', value: 76, icon: RotateCcw, color: 'text-amber-500' }];
export function Dashboard() {
  const { t } = useI18n();
  const [saved, setSaved] = useState(false);
  const score = Math.round(signals.reduce((sum, signal) => sum + signal.value, 0) / signals.length);
  return <div className="space-y-8"><section className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="mb-3 text-sm font-bold uppercase tracking-[0.2em] text-signal">Production / v2.8.0</p><h1 className="text-3xl font-black tracking-tight sm:text-5xl">{t('dashboard')}</h1><p className="mt-3 max-w-xl text-slate-500 dark:text-slate-400">{t('subtitle')}</p></div><Link to="/details"><Button variant="outline">{t('details')} <ArrowUpRight className="ms-2" size={16} /></Button></Link></section><div className="grid gap-5 lg:grid-cols-[1.1fr_2fr]"><Card className="overflow-hidden"><CardContent className="flex min-h-[280px] flex-col items-center justify-center p-8"><div className="relative flex h-48 w-48 items-center justify-center rounded-full" style={{ background: `conic-gradient(#16a394 ${score * 3.6}deg, #e2e8f0 0deg)` }}><div className="flex h-40 w-40 flex-col items-center justify-center rounded-full bg-white dark:bg-slate-900"><span className="text-5xl font-black">{score}</span><span className="text-sm text-slate-500">/ 100</span></div></div><Badge className="mt-5"><CheckCircle2 className="me-1" size={14} />{t('ready')}</Badge></CardContent></Card><Card><CardHeader><CardTitle>{t('recommendation')}</CardTitle><CardDescription>{t('last')}: {t('updated')}</CardDescription></CardHeader><CardContent><div className="rounded-xl bg-emerald-50 p-5 text-sm leading-6 text-emerald-900 dark:bg-emerald-950/40 dark:text-emerald-200">{t('recommendationText')}</div><div className="mt-6 flex items-center justify-between"><span className="text-sm text-slate-500">{t('score')}</span><span className="font-bold text-signal">+6.4% vs last release</span></div></CardContent></Card></div><section><div className="mb-4 flex items-center justify-between"><h2 className="text-xl font-bold">{t('quality')} &amp; {t('reliability')}</h2><span className="text-sm text-slate-500">4 weighted signals</span></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{signals.map(({ key, value, icon: Icon, color }) => <Card key={key}><CardContent className="p-5"><div className="flex items-center justify-between"><Icon className={color} size={22} /><span className="text-2xl font-black">{value}</span></div><p className="mt-5 text-sm font-semibold text-slate-600 dark:text-slate-300">{t(key)}</p><div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-100 dark:bg-slate-800"><div className="h-full rounded-full bg-signal" style={{ width: `${value}%` }} /></div></CardContent></Card>)}</div></section><div className="flex items-center justify-between rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center gap-3"><Activity className="text-signal" /><div><p className="font-bold">Ready for your change review?</p><p className="text-sm text-slate-500">Capture the current release decision.</p></div></div><Button onClick={() => setSaved(true)}>{saved ? t('saved') : t('save')}</Button></div></div>;
}